### ISSUE TITLE
Is it still supposed to work?

### ISSUE THREAD

**Issue by bokub** [sindresorhus/npm-email-cli#3]
Hi Sindre,

Running `npx npm-email-cli sindresorhus` throws the following error: 

```
Error: User sindresorhus doesn't exist
    at npmEmail (/home/boris/.npm/_npx/732372/lib/node_modules/npm-email-cli/node_modules/npm-email/index.js:25:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/boris/.npm/_npx/732372/lib/node_modules/npm-email-cli/cli.js:23:14
```

I have the same error no matter which username I try.

Is this CLI still supposed to work, or is it deprecated?

Thanks! :+1:

**Comment by sindresorhus** [comment]
Fixed: https://github.com/sindresorhus/npm-email-cli/releases/tag/v3.0.0

**Comment by bokub** [comment]
That was fast! Thank you
